### ISSUE TITLE
[Breaking]: Smapi says I have multiple versions, I don't

### ISSUE THREAD

**Issue by klpahner** [Annosz/UIInfoSuite#637]
### Mod Version

v2.3.7

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/059e3522697c4072b55c1b201bc987bf

### Steps to Reproduce
1. First
2. Second
3. Third
4. Fourth

**Comment by VladimirMarkelov** [comment]
From your log:

```
to fix this, delete these folders and reinstall the mod: Mods\UIInfoSuite2, Mods\UIInfoSuite2.2.3.4\UIInfoSuite2
```

So, it looks like you have installed UIInfoSuit2 into two different directories. One is `UIInfoSuite2.2.3.4\UIInfoSuite2` - I guess it is some rather old version that was unpacked with option `unpack into a directory`, and in `UIInfoSuite2` - I think it was unpack with command `unpack here`. So, you got two versions.

**Comment by klpahner** [comment]
Ok, I looked and didn't see that file at all. I will look again. If I find,
I am sorry for bothering you guys. Honestly, I am about done with modded
Stardew sadly, Smapi is messing up all of my files since the latest update.
Keep up the great work you guys do.

**Comment by VladimirMarkelov** [comment]
I am not a developer of this mod, I just love this mod and keep an eye on its issues and releases.

You can try delete `UIInfoSuite` directory and try playing again. Maybe you get another hint in SMAPI log.

As of "Smapi is messing up all of my files since the latest update", honestly, I haven't played since 1.6.9 was out yet, I'm waiting until some mods are done and published, so I can start a fresh farm with brand-new mods :-)

**Comment by klpahner** [comment]
I did finally (after an hour of searching) find the hidden traitor file. I
love the new update, however, my heavy modded challenge farm was lost to
the abyss when many mods weren't updated and smapi swears that half of the
ones I have aren't even loaded with proper files.
